TouchInstinct/RoboSwag

kotlin-extensions/src/main/java/ru/touchin/extensions/Context.kt

added openBrowser and callToPhoneNumber methods

added openBrowser and callToPhoneNumber methods

---

navigation/src/main/java/ru/touchin/roboswag/components/navigation/activities/BaseActivity.kt
navigation/src/main/java/ru/touchin/roboswag/components/navigation/keyboard_resizeable/KeyboardBehaviorDetector.kt
navigation/src/main/java/ru/touchin/roboswag/components/navigation/keyboard_resizeable/KeyboardResizeableViewController.kt

add view controller which can detect keyboard opening

---

navigation/src/main/java/ru/touchin/roboswag/components/navigation/keyboard_resizeable/KeyboardBehaviorDetector.kt

setOnApplyWindowInsetsListener was not called after unlocking phone

fix insets after unblock phone

---

tabbar-navigation/src/main/java/ru/touchin/roboswag/components/tabbarnavigation/BottomNavigationActivity.kt
tabbar-navigation/src/main/java/ru/touchin/roboswag/components/tabbarnavigation/BottomNavigationFragment.kt

Добавил метод navigateTo() в BottomNavigationActivity и в BottomNavigationFragment, чтобы была возможность снавигироваться на любую вкладку из любого места вызвав метод из `activity` и передав параметром view id нужной табы.

Possibility to navigate to certain tab programmatically using activity method

---

lifecycle/src/main/java/ru/touchin/lifecycle/extensions/ViewModelLazy.kt

added parentViewModels extension to ViewModelLazy

parentViewModels

---

tabbar-navigation/src/main/java/ru/touchin/roboswag/components/tabbarnavigation/BottomNavigationFragment.kt

Using approach `parcel.writeParcelable(this, 0)` instead of `this.writeToParcel(parcel, 0)` resolves the problem.

Fix of https://github.com/TouchInstinct/RoboSwag/issues/93

---

navigation/src/main/java/ru/touchin/roboswag/components/navigation/activities/BaseActivity.kt

Чтобы при изменении размера шрифтов из настройки системы верстка приложения не превращалась в кашу, добавлен отключаемый фриз множителя размера шрифтов

add freezing font scale factor in base activity

---

tabbar-navigation-new/src/main/java/ru/touchin/roboswag/components/tabbarnavigation_new/BottomNavigationController.kt
tabbar-navigation-new/src/main/java/ru/touchin/roboswag/components/tabbarnavigation_new/NavigationContainerFragment.kt

fixed inner navigation with navigation_new & tabbarnavigation_new

fixed inner navigation with navigation_new & tabbarnavigation_new

---

recyclerview-adapters/src/main/java/ru/touchin/adapters/DelegationListAdapter.kt

https://jira.touchin.ru/browse/VA-1563

fix outOfBoundsException in delegationListAdapter

---

navigation/build.gradle
navigation/src/main/java/ru/touchin/roboswag/components/navigation/TouchinApp.java

Revert "Migrate FB crashlytics"

---

lifecycle-rx/src/main/java/ru/touchin/lifecycle/viewmodel/BaseLiveDataDispatcher.kt

fix IllegalStateException when try to call MutableLiveData.setValue() outside main thread

---

utils/src/main/java/ru/touchin/roboswag/components/utils/spans/SpanUtils.kt

https://jira.touchin.ru/browse/LIC-2405

fix line breaks abscence in spanned text

---

kotlin-extensions/src/main/java/ru/touchin/extensions/View.kt
kotlin-extensions/src/main/java/ru/touchin/utils/ActionThrottler.kt

https://jira.touchin.ru/browse/UBRD-2042

Add throttling in `View.setOnRippleClickListener()` implementation to prevent multiple actions during ripple delay

---

storable/build.gradle
storable/src/main/java/ru/touchin/roboswag/components/utils/storables/PreferenceUtils.java

Добавляем шифрованные SharedPrefs от яндекса
https://github.com/yandextaxitech/binaryprefs

added binary prefs

---

bottom-navigation-viewcontroller/src/main/java/ru/touchin/roboswag/bottom_navigation_viewcontroller/BottomNavigationController.kt

иначе проблема https://jira.touchin.ru/browse/LIC-3240

wrong override, tried to check equality with boolean type when wrapping with navigation container was requested

---

pagination/src/main/java/ru/touchin/roboswag/pagination/ErrorItem.kt
pagination/src/main/java/ru/touchin/roboswag/pagination/PaginationAdapter.kt
pagination/src/main/java/ru/touchin/roboswag/pagination/PaginationView.kt
pagination/src/main/java/ru/touchin/roboswag/pagination/Paginator.kt
pagination/src/main/java/ru/touchin/roboswag/pagination/ProgressAdapterDelegate.kt

1. Обновил packageName.
2. Добавил возможность выбора типа обработки ошибок в пагинаторе: через алерт и через айтем в списке.
3. Обновил соответствующую логику в PaginationAdapter.

Paginator error handle mod

---

pagination/src/main/java/ru/touchin/roboswag/pagination/PaginationView.kt
pagination/src/main/java/ru/touchin/roboswag/pagination/Paginator.kt

return lost commit Paginator

---

pagination/src/main/java/ru/touchin/roboswag/pagination/PaginationAdapter.kt
pagination/src/main/java/ru/touchin/roboswag/pagination/ProgressAdapterDelegate.kt
recyclerview-adapters/build.gradle
recyclerview-adapters/src/main/AndroidManifest.xml
recyclerview-adapters/src/main/java/ru/touchin/decorators/GroupItemDecoration.kt
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/AdapterDelegate.java
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/DelegatesManager.kt
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/DelegationListAdapter.kt
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/ItemAdapterDelegate.java
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/OffsetAdapterUpdateCallback.kt
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/PositionAdapterDelegate.java
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/SimpleDataObserver.kt
recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/decorators/GroupItemDecoration.kt

GroupItemDecoration

---

mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviFragment.kt

addOnBackPressedCallback

---

views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt

added max integer path logic

---

views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt

Добавил обрезание целочисленной части.
При ограничении в 5 символов вставляем через контекстное меню: 1234657,12
Получаем: 12345,12

added trim integer path to integerPartLength

---

pagination/src/main/java/ru/touchin/roboswag/pagination/Paginator.kt

- Добавлена обработка случая, когда при загрузке первой страницы данных меньше лимита.
- Добавлена обработка случая, когда при обновлении первой страницы данных меньше лимита.

added FullState case to pagonator

---

pagination/src/main/java/ru/touchin/roboswag/pagination/Paginator.kt

paginator fix in NewPageProgress case State.FullData

paginator fix in NewPageProgress case State.FullData

---

views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt

amount with decimal decorator round

amount with decimal decorator round

---

utils/src/main/java/ru/touchin/defaults/DefaultActivityLifecycleCallbacks.kt

[Таск в jira](https://jira.touchin.ru/browse/UBRD-4825)
Исправления для поддержки android sdk версии 30

Fix due to increase target sdk version to 30

---

kotlin-extensions/build.gradle
recyclerview-adapters/build.gradle
recyclerview-adapters/src/main/java/ru/touchin/adapters/DelegationListAdapter.kt
recyclerview-calendar/build.gradle

[Тикет в Jira](https://jira.touchin.ru/browse/UBRD-4736)
Функционал `DelegationListAdapter` расширен в плане обновления списка данных, что упрощает его использование

UBRD-4736 Add new submit list functionality in DelegationListAdapter

---

views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt

при вводе большой суммы неверное округление: https://jira.touchin.ru/secure/attachment/39328/39328_video_2020-10-05_12-55-02.mp4

float to double

---

lifecycle/src/main/java/ru/touchin/lifecycle/event/ContentEvent.kt

Новый метод позволит проще трансформировать `ContentEvent<T>` в` ContentEvent<P>` без лишних `when` уловий

Add transform method into ContentEvent

---

livedata-location/build.gradle
livedata-location/src/main/java/ru/touchin/livedata/location/HuaweiLocationLiveData.kt

Добавил `HuaweiLocationLiveData`. Копия `LocationLiveData`, только с другими импортами
Пока добавляю в `ubrir/master`, потом черепикну в `master`

Add HuaweiLocationLiveData

---

mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviViewModel.kt
mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/Store.kt

removed PrettyPrint logging
https://github.com/TouchInstinct/RoboSwag/issues/180

removed PrettyPrint logging

---

navigation/src/main/java/ru/touchin/roboswag/components/navigation/viewcontrollers/ViewControllerNavigation.kt

Make state nullable after migrating to compileSdk=29

Nullable state

---

android-configs/common-config.gradle
utils/src/main/java/ru/touchin/defaults/DefaultActivityLifecycleCallbacks.kt

Обновил `targetSdk` и `compileSdk` до `30`

Update targetSdk and compileSdk up to 30

---

gradle.properties
mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviViewModel.kt
mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/di/ViewModelFactory.kt
storable/src/main/java/ru/touchin/roboswag/core/observables/storable/BaseStorable.java
storable/src/main/java/ru/touchin/roboswag/core/observables/storable/NonNullStorable.java
views/src/main/java/ru/touchin/roboswag/views/widget/AmountWithDecimalDecorator.kt

Исправил ошибки анализаторов. Для `Detekt` добавил аннотации, для `CPD` заменил аннотации на комменты (т.к. они deprecated)

Fix CPD and Detekt lint issues

---

kotlin-extensions/build.gradle
kotlin-extensions/src/main/java/ru/touchin/extensions/Context.kt
utils/src/main/java/ru/touchin/roboswag/components/utils/spans/SpanUtils.kt

Fix linter for Context.kt and SpanUtils.kt

---

kotlin-extensions/src/main/java/ru/touchin/extensions/View.kt

`findSuitableParent` - находит подходящий родитель для `snackbar`
Код взят из `com.google.android.material.snackbar.Snackbar` (там он `private`)
[Пример использования](https://betterprogramming.pub/custom-snackbars-in-android-5cb90af2728e)

Add method findSuitableParent

---

mvi-arch/build.gradle
mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviFragment.kt
mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviKeyboardResizableFragment.kt

Добавил `MviKeyboardResizableFragment`. Такой же, как и `KeyboardResizeableFragment`, только наследуется от `MviFragment`

Add MviKeyboardResizableFragment

---

kotlin-extensions/build.gradle
kotlin-extensions/src/main/java/ru/touchin/extensions/Fragment.kt
kotlin-extensions/src/main/java/ru/touchin/utils/BundleExtractorDelegate.kt

Добавил `extentions` для сохранения и получения `Bundle` аргументов

Add fragment arguments utils

---

kotlin-extensions/src/main/java/ru/touchin/extensions/Coroutines.kt

Добавил безопасный вызов корутины

Add safetylaunch

---

webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebView.kt

Потребовалось при открытии вебвью сетить куки

add set cookies functionality

---

kotlin-extensions/src/main/java/ru/touchin/extensions/Coroutines.kt

Добавил возврат `Job` в `safetyLaunch`

Make safetyLaunch return Job

---

views/src/main/java/ru/touchin/roboswag/views/CrossfadeView.kt
views/src/main/res/anim/fade_in_animation.xml
views/src/main/res/anim/fade_out_animation.xml
views/src/main/res/values/attrs.xml

Чтобы анимация была не отрывистая, добавил класс ```CrossfadeView```. Используется на УБРиРе, перенёс в ```RoboSwag``` чтобы использовать в других проектах

add crossfade view

---

views/src/main/java/ru/touchin/roboswag/views/CrossfadeView.kt

Исправил имя атрибута на ```CrossfadeView_crossfadeDefaultChild```

change name attr

---

utils/src/main/java/ru/touchin/roboswag/components/utils/SimpleTextWatcher.kt

Добавил реализацию `TextWatcher` с одним колбеком. Код взял из УБРиРа

Add SimpleTextWatcher for listening text changes

---

views/src/main/java/ru/touchin/roboswag/views/widget/Switcher.java

Добавлен метод, скрывающий все view в Switcher ViewGroup для реализации скрытия текста в https://jira.touchin.ru/browse/UBRD-8750

add hideAllChildren() in Switcher ViewGroup

---

navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/KeyboardBehaviorDetector.kt
navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/KeyboardResizeableFragment.kt
navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/StatefulKeyboardResizeableFragment.kt

Чуть-чуть порефакторил `KeyboardDetector`
- Добавил возможность добавлять сколько угодно слушателей, которые хранятся в списках
- Разделил фрагменты на `KeyboardResizeableFragment`, `MviKeyboardResizableFragment` и `StatefulKeyboardResizeableFragment`, которые наследуются от разных реализаций фрагметов для разных целей

Keyboard detector refactor

---

mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviBottomSheet.kt

Перенёс подписку на `renderState` в метод `setupRenderState()`

move to method

---

navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/KeyboardBehaviorDetector.kt

Изменил тип `activity` на более обобщенную `FragmentActivity`

Change type of argument for KeyboardBehaviorDetector

---

lifecycle/src/main/java/ru/touchin/lifecycle/LifecycleDelegates.kt
lifecycle/src/main/java/ru/touchin/lifecycle/extensions/LifecycleOwner.kt

Делегаты, которые помогают инициализировать значения при определенном событии `Lifecycle`'а

LifecycleDelegates

---

kotlin-extensions/src/main/java/ru/touchin/extensions/TypedArray.kt
utils/src/main/java/ru/touchin/roboswag/components/utils/spans/SpanUtils.kt
views/src/main/java/ru/touchin/roboswag/views/ActionTextView.kt
views/src/main/java/ru/touchin/roboswag/views/text_view/EllipsizeSpannableTextView.kt
views/src/main/java/ru/touchin/roboswag/views/text_view/MultipleActionTextView.kt
views/src/main/res/values/attrs.xml

Перенес `EllipsizeSpannableTextView` и `MultipleActionTextView` из Petshop
`EllipsizeSpannableTextView` - `TextView`, которая может хранить в себе `spannableString` и поддерживает возможность обрезаться многоточием
`MultipleActionTextView` - `TextView`, которая реализует вызов действий при нажатии на определенные подстроки

Add EllipsizeSpannableTextView and MultipleActionTextView from Petshop

---

views/src/main/java/ru/touchin/roboswag/views/text_view/StyleableSubTextView.kt

Добавил возможность динамически менять строку и подстроку

Add ability to change text and subtext dynamically

---

utils/build.gradle
utils/src/main/java/ru/touchin/roboswag/core/utils/DateFormatUtils.kt
utils/src/test/java/DateFormatUtilsTest.kt

Добавил класс `DateFormatUtils`, который пока может парсить `String` в `DateTime`
Добавил простые тесты для двух кейсов

Date time utils

---

utils/build.gradle
utils/src/test/java/DateFormatUtilsTest.kt

- Подставил для тестов зависимость `joda-time:joda-time` вместо `net.danlew:android.joda`
- Добавил переменные для версий зависимостей

Date time test fix

---

build.gradle

Migrate from bintray to maven.dev

---

navigation-viewcontroller/build.gradle
navigation-viewcontroller/src/main/java/ru/touchin/roboswag/navigation_viewcontroller/viewcontrollers/ViewControllerViewBindingDelegate.kt

* Добавил делегат для работы с байндингами во ViewController-ах

MB-13701: ViewBindingDelegate for ViewController

---

livedata-location/src/main/java/ru/touchin/livedata/location/HuaweiLocationLiveData.kt

[Не работают карты с адресами банкоматов и отделений](https://jira.lan.ubrr.ru/browse/MB-14704)

MB-14704: replace null arg with main looper to fix huawei maps on latest versions

---

base-map/src/main/java/ru/touchin/basemap/AbstractMapManager.kt
base-map/src/main/java/ru/touchin/basemap/BaseIconGenerator.kt
base-map/src/main/java/ru/touchin/basemap/BaseMapItemRenderer.kt
base-map/src/main/java/ru/touchin/basemap/MapExtension.kt
base-map/src/main/res/drawable/marker_default_icon.xml
google-map/build.gradle
google-map/src/main/java/ru/touchin/googlemap/GoogleIconGenerator.kt
google-map/src/main/java/ru/touchin/googlemap/GoogleMapItemRenderer.kt
google-map/src/main/java/ru/touchin/googlemap/GoogleMapManager.kt
google-map/src/main/java/ru/touchin/googlemap/GooglePlacemarkManager.kt
google-map/src/main/res/drawable/default_cluster_background.xml
google-map/src/main/res/layout/view_google_map_cluster_item.xml
yandex-map/src/main/java/ru/touchin/yandexmap/BitmapHelper.kt
yandex-map/src/main/java/ru/touchin/yandexmap/DefaultIconGenerator.kt
yandex-map/src/main/java/ru/touchin/yandexmap/PointModel.kt
yandex-map/src/main/java/ru/touchin/yandexmap/YandexIconGenerator.kt
yandex-map/src/main/java/ru/touchin/yandexmap/YandexMapItemRenderer.kt
yandex-map/src/main/java/ru/touchin/yandexmap/YandexMapManager.kt
yandex-map/src/main/java/ru/touchin/yandexmap/YandexPlacemarkManager.kt
yandex-map/src/main/res/layout/default_cluster_item_view.xml
yandex-map/src/main/res/layout/default_cluster_view.xml

Добавлены базовые классы для Яндекс и Гугл карт:
1. Для кластеризации маркеров (`GooglePlacemarkManager` и `YandexPlacemarkManager`)
2. Для добавления данных на карту в виде кластеров или обычных маркеров:
- `BaseMapItemRenderer`,  `YandexMapItemRenderer`,  `GoogleMapItemRenderer`
- `BaseIconGenerator`, `GoogleIconGenerator`, `YandexIconGenerator`
4. В `MapManagers` добавлены дополнительные методы для обновления положения камеры на карте (`increaseZoom`, `decreaseZoom`), а также в метод `smoothMoveCamera` добавлена возможность устанавливать `animationDuration`
```kotlin
private fun setupMap(mapView: MapView) {
mapManager = YandexMapManager(mapView = mapView, isDebug = BuildConfig.DEBUG).apply {
initialize(mapListener = listener)
}
val mapItemRenderer = …
```

MapModule update

---

text-processing/build.gradle

INTERNAL-374: Runtime ANTLR integration

---

yandex-map/build.gradle
yandex-map/src/main/java/ru/touchin/yandexmap/YandexMapManager.kt
yandex-map/src/main/java/ru/touchin/yandexmap/YandexPlacemarkManager.kt

- Обновил версию карт до 4.2.2
- Добавил отдельные методы для добавления/удаления листенеров на тап (раньше он почему-то вешался вместе с добавлением пинов на карту)
- isDebugInfoEnabled пропала из карты, поэтому удалил ее и isDebug из конструктора

Update yandex map version
