- tabbar-navigation/src/main/java/ru/touchin/roboswag/components/tabbarnavigation/BottomNavigationFragment.kt
Now getter of field `viewControllerState` returns new instance every time it be called instead of returning the same instance.
> TabData modifying

- navigation/src/main/java/ru/touchin/roboswag/components/navigation/keyboard_resizeable/KeyboardBehaviorDetector.kt
Без onApplyWindowInsets теряются настройки инсетов по дефолту. Это не всегда важно, но на ликарде вылезло
> Fixed nav. bar

- lifecycle/src/main/java/ru/touchin/lifecycle/extensions/ImmutableExt.kt
Before:
After:
Imporvement: You need to specify value type of LiveData only once.
> lifecycle: add toLiveData extension for easy immutable live data fields

- pagination/src/main/java/ru/touchin/roboswag/pagination/Paginator.kt
Если при загрузке данных, получен массив меньше, чем размер страницы, то необходимо считать, что данные полностью загружены. Иначе отправляется лишний запрос, в ответе на который приходит пустой массив.
> added paginator full state if itemList < pageSize

- navigation-new/build.gradle
- navigation/build.gradle
> Add "noinspection" to suppress crashlytics outdate warning in order to proceed static analysis

- recyclerview-adapters/src/main/java/ru/touchin/adapters/DelegationListAdapter.kt
[UBRD-4511](https://jira.touchin.ru/browse/UBRD-4511)
Возвращаю возможность делать submit с callback, полезно когда нужно выполнить действие после применения всех изменений. Для починки этого бага как раз это будет учень удобно.
> Add submit with callback into DelegationListAdapter

- recyclerview-adapters/src/main/java/ru/touchin/adapters/DelegationListAdapter.kt
This reverts commit 2ddc08c22b9f91984c901805a3727ce975b55c6f.
Убрал callback в submitList из master/ubrir до обновления recyclerview до 1.1.0
> Revert "Add submit with callback into DelegationListAdapter"

- navigation/src/main/java/ru/touchin/roboswag/components/navigation/TouchinApp.java
Вынес всю инициализацию приложения в метод `onMainProcessCreate`, который вызывается только при создании основного процесса. Далее этот метод будет использоваться в наследниках для инициализации библиотек только в главном процессе, в частности библиотеки антифрода от group-ib.
> Add open onMainProcessCreate method for descendants usage

- recyclerview-calendar/src/main/java/ru/touchin/calendar/CalendarUtils.java
[UBRD-6128](https://jira.touchin.ru/browse/UBRD-6128)
Исправил расчет диапазона для `CalendarEmptyItem` в конце месяца, иначе диапазон перекрывался с диапазоном последующего `CalendarHeaderItem`
> UBRD-6128 Fix displaying first day of month in calendar

- recyclerview-adapters/build.gradle
- recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/DelegationListAdapter.kt
Вернул метод `submitList` с коллбэком + повысил версию RecyclerView
У нас и так используется версия RecyclerView 1.1.0 из-за подключенного ViewPager2, поэтому имеет смысл использовать его возможности вместо костылей с post после submit
> Add recyclerview submit with callback + up version

- webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebView.kt
- webview/src/main/java/ru/touchin/roboswag/webview/web_view/BaseWebViewClient.kt
- webview/src/main/java/ru/touchin/roboswag/webview/web_view/WebViewCallback.kt
- Фикс вылета вебвью если ссылка isBlank или невалидная (выбивает в OnReceivedError), была попытка сохранить куки, а они null, поэтому вылетало
- Фикс дергающегося скролла (проблема не решена полностью, если вызвать onSwipeRefresh, то страница будет немного подёргиваться, т.к. перезагружается), отключение мешающего горизонтального скролла страницы и подгон под размер экрана
- Увеличение производительности сменой на LAYER_TYPE_HARDWARE
- loadUrl: проверка ссылки на null, тогда она становится пустой строкой и в OnPageFinished опрелеляется как "about:blank", после чего отобразится error_layout, иначе при null попадает в бесконечную загрузку
- Фикс пропадающего сообщения об отсутствии интернета (из кэша) на банках, в OnReceivedError вызывалась лишний раз pageFinished() со сменой состояния …
> fix webview crashes

- kotlin-extensions/src/main/java/ru/touchin/extensions/CharSequence.kt
- utils/build.gradle
- utils/src/main/java/ru/touchin/roboswag/components/utils/spans/SpanUtils.kt
- views/src/main/java/ru/touchin/roboswag/views/ActionTextView.kt
- views/src/main/res/values/attrs.xml
Добавил `View` для упрощения создания `ClickableSpan` у части текста. В параметры `View` передается `actionText` - кликабельная подстрока и `actionColor` - цвет кликабельной подстроки
Пример:
> Add TextView with ClickableSpan substring

- kotlin-extensions/src/main/java/ru/touchin/extensions/Context.kt
resolveActivity возвращает null начиня с API level 30. вариант первый - добавить queries. вариант второй - запускать активити без проверки. из-за того, что тут точно открывается только браузер и чтобы не менять сейчас манифест во всех проектах второй вариант кажется оптимальным.
https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30
> fix open browser

- mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviKeyboardResizableFragment.kt
Убрал инициализацию `keyboardBehaviorDetector` из фрагмента, т.к. получалось, что у нас по одному `detector`'у на каждый фрагмент. Перенес его инициализацию в `SingleActivity` проекта
> Fix initializing KeyboardBehaviorDetector

- navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/KeyboardBehaviorDetector.kt
```setOnApplyWindowInsetsListener``` перестаёт следить за изменениями, если были запрошены permissions. Решил с установкой слежения в ```onResume```
> Fix windowlistener when setting permissions

- mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviKeyboardResizableFragment.kt
При смерти и восстновлении процесса (с опцией "Вытеснение фоновых активностей" и открытой клавиатурой) клавиатура старого процесса остается открытой, из-за этого происходит конфликт в keyboardBehaviorDetector и он перестает отслеживать клавиатуру текущего процесса.
Из-за этого возникала ошибка: https://jira.touchin.ru/browse/PET-318
Если же форсировано скрывать клавиатуру в onPause() MviKeyboardResizableFragment, при перезапуске keyboardBehaviorDetector будет корректно отслеживать состояние клавиатуры.
> Fix keyboard behavior detection after recreating activity with opened keyboard

- navigation-cicerone/src/main/java/ru/touchin/roboswag/navigation_cicerone/flow/FlowFragment.kt
Когда `FlowFragment` является не самым верхнеуровневым фрагментом, методом `router.exti()` отрабатывает неверно. В `SupportAppNavigator` отрабатывает следующее:
```
protected void fragmentBack() {
if (localStackCopy.size() > 0) {
fragmentManager.popBackStack();
localStackCopy.removeLast();
} else {
activityBack();
}
}
```
Т.е. если в текущий flow-фрагмент не имеет ничего вложенного, то `Activity` будет закрыта. Чтобы этого избежать, добавил проверку на 
1) Является ли текущий фрагмент последним
2) Есть ли у фрагмента, фрагмент родитель
Если да, то просто делаем `popBackStack`, если нет - `router.exit()`
> Fix navigating back inside nested features

- mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/FullscreenBottomSheetDialog.kt
Для класса ```FullscreenBottomSheetDialog``` добавил возможность делать отступ сверху. Если отступ не нужен, то ```BottomSheet``` будет на развёрнут на весь экран
> add top padding to fullscreen bottom sheet

- android-configs/app-config.gradle
- lifecycle/src/main/java/ru/touchin/lifecycle/scope/ViewCoroutineScope.kt
- lifecycle/src/main/res/values/strings.xml
- mvi-arch/build.gradle
- navigation-cicerone/build.gradle
- Плагин `kotlin-android-extensions` - `deprecated`. Используется для предоставления `Parcelize`, поэтому заменил на `kotlin-parcelize` - https://github.com/TouchInstinct/RoboSwag/pull/245/commits/1b994bab0ea74c67880edb39b8dbbbc5889bfadf
- Повысил версию dagger до `2.34`, чтобы сделать ее совместимой с `kotlin 1.5+` - https://github.com/TouchInstinct/RoboSwag/pull/245/commits/902c029a295e7993ca159602529dc5e7cdd3838e
- Добавил кастомный `CoroutineScope` для `View` - https://github.com/TouchInstinct/RoboSwag/pull/245/commits/cab47a058c765f1b63e1a306bbb60b6f4be3a9ba
> Coroutine scope view

- recyclerview-adapters/build.gradle
- recyclerview-adapters/src/main/java/ru/touchin/roboswag/recyclerview_adapters/adapters/SubmittablePagingAdapter.kt
Добавил подкласс `PagingDataAdapter` с возможностью  с делать обновление списка элементов.
`PagingDataAdapter` не умеет в локальное обновление данных через обычный `submitList` как у стандартного `Adapter`
[Реализация на основе этого примера](https://medium.com/tech-takeaways/how-to-update-paginated-data-with-the-android-paging-3-library-ef2d8581e77f)
Возможные доработки:
- перенести сравнение элементов на бэкграунд поток (предполагается, что в `items` передается только те элементы, которые были обновлены, поэтому это не так больно)
- обновить библиотеку `paging3` до `3.1.0` (сейчас на петшопе используется именно `3.0.0-alpha06`, поэтому использую ее)
> SubmittablePagingAdapter

- lifecycle-rx/src/main/java/ru/touchin/lifecycle/viewmodel/RxViewModel.kt
- lifecycle-rx/src/main/java/ru/touchin/lifecycle/viewmodel/TestableLiveDataDispatcher.kt
1. В RxViewModel тип liveDataDispatcher заменил с BaseLiveDataDispatcher на интерфейс, чтобы можно было удобно подменять эту зависимость. 
2. Добавил TestableLiveDataDispatcher, в котором нет андроидовских классов, чтобы лайвдаты можно было тестировать на JVM, а не эмуляторе
> Add testing utils

- mvi-arch/build.gradle
- mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/core/MviViewModel.kt
- mvi-arch/src/main/java/ru/touchin/roboswag/mvi_arch/mediator/LoggingMediator.kt
Убрал зависимость `pretty-print` в модуле с mvi, так как:
- он не совместим с api < 24 (проблема все еще осталась), и строка, где он использовался вообще была закомменчена
- он добавлял зависимость, которая занимает в apk почти 10 мб
```
+--- com.tylerthrailkill.helpers:pretty-print:2.0.2
+--- com.ibm.icu:icu4j:63.1
```
> Remove pretty-print dependency from mvi module

- navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/KeyboardBehaviorDetector.kt
[PET-2763](https://jira.touchin.ru/browse/PET-2763) - появился баг на Петшопе (видимо после обновления material) из-за того, что неправильно срабатывает `KeyboardBehaviorDetector`
В связке "открытая клавиатура" + DNKA + лок/анлок `startNavigationBarHeight` инициализируются, как будто клавиатура изначально открыта, хотя это не так, после чего определение открытой клавиатуры работает противоположно реальности. Добавил фикс для такой ситуации
> Fix KeyboardBehaviorDetector

- navigation-base/src/main/java/ru/touchin/roboswag/navigation_base/keyboard_resizeable/KeyboardBehaviorDetector.kt
[PET-3233](https://jira.touchin.ru/browse/PET-3233) - Пропадает таббар после разблокировки телефона
Еще небольшой фикс `KeyboardDetector`. На если открыть МП на самсунге, заблокировать и разблокировать отпечатком или СМАРТ-ЧАСАМИ, то `bottomInset` на секунду принимал значение 0 и дальше всё шло не по плану
тестер уже посмотрел
> PET-3233: fix KeyboardBehaviorDetector when bottomInset == 0

- navigation-viewcontroller/build.gradle
модуль navigation-viewcontroller унаследовал от давнего общего модуля navigation зависимости, в которых он не нуждается (в основном использовались в классе TouchinApp, который сейчас перешел в модуль base-navigation)
при обновлении крашлитики одна из них стала вызывать краш на старте приложения. `implementation("com.crashlytics.sdk.android:crashlytics")` тянула за собой `io.fabric.sdk`, которая в свою очередь искала сгенерированную плагином строку `"com.crashlytics.android.build_id"`, но при обновлении она сменила название
```
LEGACY_MAPPING_FILE_ID_RESOURCE_NAME = "com.crashlytics.android.build_id";
MAPPING_FILE_ID_RESOURCE_NAME = "com.google.firebase.crashlytics.mapping_file_id"
```
стектрейс ошибки:
> fix unnecessary dependencies in :navigation-view-controller module
